//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stride.Irony {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stride.Irony.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create AST node for non-terminal [{0}], error: {1}.
        /// </summary>
        internal static string ErrFailedCreateNode {
            get {
                return ResourceManager.GetString("ErrFailedCreateNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The last term of production containing SyntaxError must be a terminal. NonTerminal: {0}.
        /// </summary>
        internal static string ErrLastTermOfErrorProd {
            get {
                return ResourceManager.GetString("ErrLastTermOfErrorProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List non-terminals cannot be marked transient; list: ({0}).
        /// </summary>
        internal static string ErrListCannotBeTransient {
            get {
                return ResourceManager.GetString("ErrListCannotBeTransient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No closing pair for opening symbol {0}.
        /// </summary>
        internal static string ErrNoClosingBrace {
            get {
                return ResourceManager.GetString("ErrNoClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning: AstNodeType or AstNodeCreator is not set on non-terminals: {0}..
        /// </summary>
        internal static string ErrNodeTypeNotSetOn {
            get {
                return ResourceManager.GetString("ErrNodeTypeNotSetOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non-terminal {0} has uninitialized Rule property..
        /// </summary>
        internal static string ErrNtRuleIsNull {
            get {
                return ResourceManager.GetString("ErrNtRuleIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Syntax error, expected: {0}.
        /// </summary>
        internal static string ErrParserUnexpInput {
            get {
                return ResourceManager.GetString("ErrParserUnexpInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ({0}) term passed as &apos;root&apos; paramater to parserr is not Root or snippet root of the grammar. Add it to SnippetRoots set in grammar constructor..
        /// </summary>
        internal static string ErrRootNotRegistered {
            get {
                return ResourceManager.GetString("ErrRootNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Root property of the grammar is not set..
        /// </summary>
        internal static string ErrRootNotSet {
            get {
                return ResourceManager.GetString("ErrRootNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reduce-reduce conflict. State {0}, lookaheads: {1}. Selected reduce on first production in conflict set..
        /// </summary>
        internal static string ErrRRConflict {
            get {
                return ResourceManager.GetString("ErrRRConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rule for NonTerminal {0} contains null as an operand in position {1} in one of productions..
        /// </summary>
        internal static string ErrRuleContainsNull {
            get {
                return ResourceManager.GetString("ErrRuleContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shift-reduce conflict. State {0}, lookaheads [{1}]. Selected shift as preferred action..
        /// </summary>
        internal static string ErrSRConflict {
            get {
                return ResourceManager.GetString("ErrSRConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transient non-terminal must have zero or one non-punctuation child nodes; non-terminals: {0}..
        /// </summary>
        internal static string ErrTransientNtMustHaveOneTerm {
            get {
                return ResourceManager.GetString("ErrTransientNtMustHaveOneTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected end of file..
        /// </summary>
        internal static string ErrUnexpEof {
            get {
                return ResourceManager.GetString("ErrUnexpEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected indentation..
        /// </summary>
        internal static string ErrUnexpIndent {
            get {
                return ResourceManager.GetString("ErrUnexpIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unmatched closing brace &apos;{0}&apos;..
        /// </summary>
        internal static string ErrUnmatchedCloseBrace {
            get {
                return ResourceManager.GetString("ErrUnmatchedCloseBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}({1}:{2}).
        /// </summary>
        internal static string FmtRowCol {
            get {
                return ResourceManager.GetString("FmtRowCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string LabelActionAccept {
            get {
                return ResourceManager.GetString("LabelActionAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operator, shift to {0}/reduce on {1}..
        /// </summary>
        internal static string LabelActionOp {
            get {
                return ResourceManager.GetString("LabelActionOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reduce on {0}.
        /// </summary>
        internal static string LabelActionReduce {
            get {
                return ResourceManager.GetString("LabelActionReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shift to {0}.
        /// </summary>
        internal static string LabelActionShift {
            get {
                return ResourceManager.GetString("LabelActionShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Unknown action type).
        /// </summary>
        internal static string LabelActionUnknown {
            get {
                return ResourceManager.GetString("LabelActionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [end-of-statement].
        /// </summary>
        internal static string LabelEosLabel {
            get {
                return ResourceManager.GetString("LabelEosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Key symbol).
        /// </summary>
        internal static string LabelKeySymbol {
            get {
                return ResourceManager.GetString("LabelKeySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Keyword).
        /// </summary>
        internal static string LabelKeyword {
            get {
                return ResourceManager.GetString("LabelKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parsing conflict resolved in code..
        /// </summary>
        internal static string MsgTraceConflictResolved {
            get {
                return ResourceManager.GetString("MsgTraceConflictResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operator - resolved to {0}.
        /// </summary>
        internal static string MsgTraceOpResolved {
            get {
                return ResourceManager.GetString("MsgTraceOpResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Popped state from stack, pushing {0}.
        /// </summary>
        internal static string MsgTracePoppedState {
            get {
                return ResourceManager.GetString("MsgTracePoppedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECOVERING: {0}.
        /// </summary>
        internal static string MsgTraceRecoverAction {
            get {
                return ResourceManager.GetString("MsgTraceRecoverAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAILED TO RECOVER.
        /// </summary>
        internal static string MsgTraceRecoverFailed {
            get {
                return ResourceManager.GetString("MsgTraceRecoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECOVERING: popping stack, looking for state with error shift.
        /// </summary>
        internal static string MsgTraceRecovering {
            get {
                return ResourceManager.GetString("MsgTraceRecovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECOVERING: Reached end of error production, reducing..
        /// </summary>
        internal static string MsgTraceRecoverReducing {
            get {
                return ResourceManager.GetString("MsgTraceRecoverReducing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RECOVERED.
        /// </summary>
        internal static string MsgTraceRecoverSuccess {
            get {
                return ResourceManager.GetString("MsgTraceRecoverSuccess", resourceCulture);
            }
        }
    }
}
