<!--
***********************************************************************************************
  Stride.Native.Libs.targets

  Build file post-included after the building of the project to configure the linking of
  native libraries libCompilerRt and libCelt for "libstrideaudio.dll".

  Copyright (C) 2021 Stride and its contributors
***********************************************************************************************
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <StrideNativePathLibsWindows>libCompilerRt.lib libCelt.lib</StrideNativePathLibsWindows>
  </PropertyGroup>
</Project>
