// Copyright (c) .NET Foundation and Contributors (https://dotnetfoundation.org)
// Copyright (c) 2018-2021 Stride and its contributors (https://stride3d.net)
// Copyright (c) 2011-2018 Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Copyright (c) 2015 Sockets-for-PCL, Ryan Davis
// See the LICENSE.md file in the project root for full license information.

// <auto-generated /> (skip analyzers, file from external source)

namespace Sockets.Plugin.Abstractions
{
    /// <summary>
    /// The connection state of an interface.
    /// </summary>
    enum CommsInterfaceStatus
    {
        /// <summary>
        /// The state of the interface can not be determined.
        /// </summary>
        Unknown,

        /// <summary>
        /// The interface is connected. 
        /// </summary>
        Connected,

        /// <summary>
        /// The interface is disconnected.
        /// </summary>
        Disconnected,
    }
}
