// Copyright (c) 2018-2020 Xenko and its contributors (https://xenko.com)
// Copyright (c) 2011-2018 Silicon Studio Corp. (https://www.siliconstudio.co.jp)
// Copyright (c) 2015 Sockets-for-PCL, Ryan Davis
// Distributed under the MIT license. See the LICENSE.md file in the project root for more information.

// <auto-generated /> (skip analyzers, file from external source)

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Text;
using System.Threading.Tasks;

namespace Sockets.Plugin
{
    partial class CommsInterface
    {
        /// <summary>
        /// This method sits in a partial class definition on each native platform and retrieves the
        /// netmask in whatever way it can be done for each platform.
        /// </summary>
        protected static IPAddress GetSubnetMask(UnicastIPAddressInformation ip)
        {
            return ip.IPv4Mask;
        }
    }
}
